################################################################################
# > ⚠️ AI-Generated Module / Generated by Bob, an AI assistant powered by IBM watsonx
################################################################################

terraform {
  required_version = ">= 1.5.7"

  cloud {
    organization = "jose-merchan"
    workspaces {
      name = "eks-infra-vcs"
    }
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.35"
    }
  }
}
